license = "GPL-v3"
author = "Emile Cadorel <ecadorel@gmail.com>"
libraries = ["gmp", "mpfr"]
type = "library"
description = "Ymir bootstrap compiler"
version = "1.1.0"
name = "ymirc"

[dependencies]

[registry]
git = "git@github.com:GNU-Ymir/bootstrap.git"
