license = "GPL-v3"
author = "Emile Cadorel <ecadorel@gmail.com>"
libraries = []
type = "executable"
description = "Ymir bootstrap compiler"
version = "0.1.3"
name = "ymirc"

[dependencies]

[registry]
git = "https://github.com/GNU-Ymir/bootstrap.git"
