license = "GPL-v3"
author = "Emile Cadorel <ecadorel@gmail.com>"
libraries = []
type = "executable"
description = "Ymir bootstrap compiler"
version = "0.1.2"
name = "ymirc"

[dependencies]

[registry]
git = "git@github.com:GNU-Ymir/bootstrap.git"
